appId: net.tai2.voicepost
---
- clearState
- launchApp
- tapOn: 設定画面を開く
- tapOn: ログイン
- runFlow:
    when:
      platform: Android
    file: subflows/dropbox_oauth_android.yml
- runFlow:
    when:
      platform: iOS
    file: subflows/dropbox_oauth_ios.yml
- tapOn: ログアウト
- assertVisible: ログイン