name: Release

on:
  workflow_dispatch:

jobs:
  create-release-branch-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      # Branch format: {YYYY.MM.DD}-{HH.MM}
      - run: |
          echo "RELEASE_DATE=$(date +'%Y.%m.%d-%H.%M')" >> $GITHUB_ENV

      - name: Create a release branch
        env:
          RELEASE_DATE: ${{ env.RELEASE_DATE }}
        shell: bash
        run: |
          git checkout -b release/$RELEASE_DATE
          git fetch origin main
          git fetch origin develop
          git merge origin/develop
          git push origin release/$RELEASE_DATE

      - name: Create a Release Pull Request
        env:
          RELEASE_DATE: ${{ env.RELEASE_DATE }}
        shell: bash
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_FOR_VOICE_POST }}" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "{\"head\":\"release/${RELEASE_DATE}\",\"base\":\"main\",\"title\":\"Release ${RELEASE_DATE}\"}"
